/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import type { JSX } from 'react';

export function CV(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/cv.glb') as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paper_paper_1_0.geometry}
        material={nodes.paper_paper_1_0.material}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.375, 1, 0.002]}
      />
    </group>
  );
}

useGLTF.preload('/cv.glb');
