/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import type { JSX } from 'react'

export function NameTag(props: JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/card.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.2, 0]} scale={[1.6515, 1.7, 1.3]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_2.geometry}
          material={nodes.box_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_4.geometry}
          material={nodes.box_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_5.geometry}
          material={nodes.box_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_6.geometry}
          material={nodes.box_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_7.geometry}
          material={nodes.box_7.material}
        />
      </group>
      <group position={[0, 0.11, 0]} scale={[1.143, 1.5, 0.651]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card_1.geometry}
          material={nodes.card_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card_3.geometry}
          material={nodes.card_3.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clip.geometry}
        material={nodes.clip.material}
        position={[0, 0, 0]}
      >
        <meshStandardMaterial color="#63ff00" metalness={0.2} roughness={0.1} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clamp.geometry}
        material={nodes.clamp.material}
        position={[0, 0, 0]}
      >
        <meshStandardMaterial color="#63ff00" metalness={0.2} roughness={0.1} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/card.glb')
