/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import type { JSX } from 'react'


export function NameTag(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/card.glb') as any
  return (
    <group {...props} dispose={null}>
      <group position={[-0.002, 0.08, 0]} scale={[1.101, 1.176, 0.927]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_1.geometry}
          material={nodes.box_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_2.geometry}
          material={nodes.box_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_3.geometry}
          material={nodes.box_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_4.geometry}
          material={nodes.box_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_5.geometry}
          material={nodes.box_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_6.geometry}
          material={nodes.box_6.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.box_7.geometry}
          material={nodes.box_7.material}
        />
      </group>
      <group position={[-0.002, 0, 0.001]} scale={[0.762, 1, 0.434]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card_1.geometry}
          material={nodes.card_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card_2.geometry}
          material={nodes.card_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card_3.geometry}
          material={nodes.card_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card_4.geometry}
          material={nodes.card_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card_5.geometry}
          material={nodes.card_5.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.card_6.geometry}
          material={nodes.card_6.material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clip.geometry}
        material={nodes.clip.material}
        position={[0, -0.358, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.clamp.geometry}
        material={nodes.clamp.material}
        position={[0, -0.358, 0]}
      />
    </group>
  )
}

useGLTF.preload('/card.glb')
