/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import type { JSX } from 'react';

export function Printer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/printer.glb') as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={nodes.Object_2.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={nodes.Object_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={nodes.Object_5.material}
        >
          <meshStandardMaterial
            color="#63ff00"
            metalness={0.2}
            roughness={0.1}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={nodes.Object_6.material}
          position={[0.001, 0, 0]}
          rotation={[0.003, -0.004, -0.009]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Post_it_note}
          position={[0.023, 0.096, 0.233]}
          rotation={[Math.PI / 2, -0.583, 0]}
          scale={5.949}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/printer.glb');
