/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import type { JSX } from 'react';

const BASE_URL = import.meta.env.VITE_BASE_PATH;

export function Printer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(`${BASE_URL}printer.glb`) as any;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-0.401, 0.129, 0.198]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.427, 0.427, 0.572]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_1.geometry}
            material={nodes.Box_1.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_2.geometry}
            material={nodes.Box_2.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_3.geometry}
            material={nodes.Box_3.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_4.geometry}
            material={nodes.Box_4.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_5.geometry}
            material={nodes.Box_5.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Box_6.geometry}
            material={nodes.Box_6.material}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={nodes.Object_3.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={nodes.Object_4.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={nodes.Object_5.material}
        >
          <meshStandardMaterial
            color="#63ff00"
            metalness={0.2}
            roughness={0.1}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={nodes.Object_6.material}
          position={[0.001, 0, 0]}
          rotation={[0.003, -0.004, -0.009]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.Post_it_note}
          position={[0.023, 0.096, 0.233]}
          rotation={[Math.PI / 2, -0.583, 0]}
          scale={5.949}
        />
      </group>
    </group>
  );
}

useGLTF.preload(`${BASE_URL}printer.glb`);
